[snowflake]
account = "GCOJMSS.BCB72938"
user = "PBARKLEY"
password = "Pb112379!Snowflake!2"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
